server:
  port: 7094
  servlet:
    context-path: /customize
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.1.213:1521/shbw_tcc
    username: skfwq_servlet
    password: skfwq_servlet
    driver-class-name: oracle.jdbc.OracleDriver
    druid:
      initialSize: 10
      minIdle: 10
      maxActive: 100
      maxWait: 10000
      timeBetweenEvictionRunsMillis: 18800
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      stat-view-servlet:
        enabled: false
      web-stat-filter:
        enabled: false
      filter:
        config:
          enabled: false
    type: com.alibaba.druid.pool.DruidDataSource
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 去除druid配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的字段实体名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
customize:
  query-company-info-url: https://swgxs.baiwangjs.com/agentiscloud/cloud/queryUniqueSign
  query-goods-info-url: https://swgxs.baiwangjs.com/agentiscloud/cloud/query/goods
  push-invoice-doc-url: https://swgxs.baiwangjs.com/agentiscloud/cloud/addReceiptUrl