server:
  port: 7094
  servlet:
    context-path: /customize

customize:
  query-company-info-url: https://api.baiwangjs.com/swgx-saas/agentinvoiceservice-cloudservice-cloudservice/agentiscloud/cloud/queryUniqueSign
  query-goods-info-url: https://api.baiwangjs.com/swgx-saas/agentinvoiceservice-cloudservice-cloudservice/agentiscloud/cloud/query/goods
  push-invoice-doc-url: https://api.baiwangjs.com/swgx-saas/agentinvoiceservice-cloudservice-cloudservice/agentiscloud/cloud/addReceiptUrl

swgx:
  http:
    ak_id: 91310000MA1HNBYL8J_xOgNgw4t9JD88Z705BXj
    ak_secret: Z8aLLQj3ovNUid929ZSH1aNs